---
# tasks file for azure-subnets
- name: Create/Update Subnets
  azure_rm_subnet:
    name: "{{ subnet_name }}"
    resource_group: "{{ resource_group }}"
    virtual_network_name: "{{ vnet_name }}"
    address_prefix_cidr: "{{ subnet_address_prefix }}"
    security_group: "{{ nsg_name | default(omit, true) }}"
    route_table: "{{ route_table | default(omit, true) }}"
